# -*- coding: utf-8 -*-
"""InternNova Week1_Assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1adqVvpDK4awZ9gEXP9cV5J6aE7v9jfno
"""

# Intern Nova Week 1 Assignment: Python Fundamentals for Data Analytics
# Task 1: Python Basics
print("Welcome to Intern Nova Internship Task 1!")

name = input("Enter your Name:")
college_name = input("Enter your College Name:")
branch = input("Enter your Branch:")

print("\nStudent Information")
print("Name:", name)
print("College Name:", college_name)
print("Branch:", branch)

# Task 2: Variables & Data Types
age = 20
percentage = 89.96
name = "Lily"
student = True

print("Integer:", age)
print("Data type:", type(age))

print("\nFloat:", percentage)
print("Data type:", type(percentage))

print("\nString:", name)
print("Data type:", type(name))

print("\nBoolean:", student)
print("Data type:", type(student))

# Task 3: Operators
num1 = float(input("Enter the first number:"))
num2 = float(input("Enter the second number:"))

print("\nAddition:", num1 + num2)
print("Subtraction:", num1 - num2)
print("Multiplication:", num1 * num2)
print("Division:", num1 / num2)
print("Modulus:", num1 % num2)

# Task 4: Conditional Statements
marks = float(input("Enter your marks:"))
if marks >= 90: grade = "A"
elif marks >= 75: grade = "B"
elif marks >= 60: grade = "C"
else: grade = "Fail"
print("Marks:", marks)
print("Grade:", grade)

# Task 5: Loops
# Print numbers from 1 to 20 using a for loop

print("Numbers from 1 to 20:")
for i in range(1,21):
  print(i)

# Print the multiplication table of any number.
num = int(input("Enter a number: "))
print("\nMultiplication table of", num)
for i in range(1,11):
  print(num, "x", i, "=", num * i)

# Print even numbers from 1 to 50 using a while loop.
print("Even numbers from 1 to 50:")
num = 2
while num <= 50:
  print(num)
  num += 2

# Task 6: Functions
def sq(num):
  return num * num

def avg(num1, num2, num3):
  return (num1 + num2 + num3) / 3

num = float(input("Enter a number: "))
print("Square:", sq(num))
num1 = float(input("\nEnter the first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))
avg = avg(num1, num2, num3)
print("Average:", avg)

# Task 7: Strings & Collections
# String operations
text = "Data Analytics"
print("Uppercase:", text.upper())
print("Lowercase:", text.lower())
print("Replace:", text.replace("Data", "Business"))
print("Position of 'Analytics':", text.find("Analytics"))

# List operations
fruits = ["Mango", "Apple", "Grapes"]
print("Original List:", fruits)

fruits.append("Tomato")
print("\nAfter append:", fruits)

fruits.remove("Tomato")
print("After remove:",fruits)

fruits.sort()
print("After sort:", fruits)

# Tuple creation and indexing
subjects = ("Python", "SQL", "Power BI", "Excel")

print("Tuple:", subjects)
print("First element:", subjects[0])
print("Third element:", subjects[2])

# Dictionary storing student information
student = {
    "Name" : "Lily",
    "Subjects" : ["Math", "Science", "English"],
    "Marks" : [95, 92, 98]
}
print(student)

# Set operations
sub = {"Math", "Science", "English"}
print("Subjects:", sub)
sub.add("Social-Science")
print("After adding:", sub)
sub.remove("English")
print("After removing:", sub)

# Task 8: Basic File Handling
# Creating the file and writing introduction

with open("introduction.txt", "w") as f:
    f.write("Hello, my name is Sushma.\n")
    f.write("My branch is Computer Science and Design.\n")
    f.write("I am interested in Data Analytics.")

print("Data written successfully.")

# Read and display the file

with open("introduction.txt", "r") as f:
    data = f.read()

print(data)

# Task 9: Mini Python Project
#Develop a Student Record Management System using Python.
students = []

while True:
    print("\n--- Student Record Management System ---")
    print("1. Add Student")
    print("2. Display Students")
    print("3. Search Student")
    print("4. Delete Student")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        name = input("Enter student name: ")
        age = int(input("Enter age: "))
        branch = input("Enter branch: ")

        stu = {
            "name": name,
            "age": age,
            "branch": branch
        }

        students.append(stu)
        print("Student added successfully.")

    elif choice == "2":
        if len(students) == 0:
            print("No student records found.")
        else:
            print("\nStudent Records:")
            for stu in students:
                print(stu)

    elif choice == "3":
        name = input("Enter student name to search: ")

        found = False

        for stu in students:
            if stu["name"].lower() == name.lower():
                print("Student found:", stu)
                found = True
                break

        if not found:
            print("Student not found.")

    elif choice == "4":
        name = input("Enter student name to delete: ")

        for stu in students:
            if stu["name"].lower() == name.lower():
                students.remove(stu)
                print("Student deleted successfully.")
                break
        else:
            print("Student not found.")

    elif choice == "5":
        print("Thank you!")
        break

    else:
        print("Invalid choice.")